<?php
namespace WA_ACF_PTM\Admin\Services;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class Temp_File_Service {
	/**
	 * Delete a temporary file generated by the plugin.
	 */
	public static function delete( string $path ): void {
		if ( '' !== $path && file_exists( $path ) && is_file( $path ) ) {
			wp_delete_file( $path );
		}
	}
}
