<?php
namespace WA_ACF_PTM\Admin\Services;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class Temp_File_Service {
	/**
	 * Delete a temporary file generated by the plugin.
	 */
	public static function delete( string $path ): void {
		if ( self::is_safe_temp_file( $path ) ) {
			wp_delete_file( $path );
		}
	}


	/**
	 * Delete temporary upload rows generated by this plugin.
	 *
	 * @param array<int,array<string,mixed>> $uploads Uploaded file rows containing a file path.
	 */
	public static function delete_upload_files( array $uploads ): void {
		foreach ( $uploads as $upload ) {
			if ( ! empty( $upload['file'] ) && is_string( $upload['file'] ) ) {
				self::delete( (string) $upload['file'] );
			}
		}
	}

	/**
	 * Confirm a path points to a real file inside WordPress' temporary directory.
	 */
	public static function is_safe_temp_file( string $path ): bool {
		if ( '' === $path || ! file_exists( $path ) || ! is_file( $path ) ) {
			return false;
		}

		$temp_dir = realpath( get_temp_dir() );
		$file     = realpath( $path );

		if ( false === $temp_dir || false === $file ) {
			return false;
		}

		$temp_dir = wp_normalize_path( trailingslashit( $temp_dir ) );
		$file     = wp_normalize_path( $file );

		return 0 === strpos( $file, $temp_dir );
	}
}
